### ISSUE TITLE
Poll: Writing styles

### ISSUE THREAD

**Issue by madx** [lukemt/obsidian-feeds#12]
Hi everyone!

We are planning to streamline the plugin's settings and make sure it is really simple. We currently have a bunch of options affecting the filtering of which bullet points to show. These settings can be Vault-wide through the plugin's settings tab, or specified as YAML in the code-block that triggers the rendering of your feed.

In order to be able to satisfy as many workflows as possible, we would like to know what's your current way of working with bullet points and what you would like to accomplish with this plugin.

If you want to help us, please respond to this issue with either a sample of your writing and the desired output in your Feed, or with a proper description of what you are trying to accomplish.

Edit: This is needed for #7 and related to #10

**Comment by madx** [comment]
Here's an example response with my current style and what I need the plugin to do for me!

## Dailies

I keep weekly notes with one header per day (formatted as `YYYY-MM-DD`). I wrote bullet points where the topic is the first part of the bullet, followed by a space and a dash. Below is an excerpt of such notes:

```markdown
### 2023-11-08

[[Pro/MyCompany/2023-11-08 - Daily Work Note|2023-11-08 - Daily Work Note]]

- [[Flux/PKM|PKM]] - J'ai simplifié mon système de capture en utilisant uniquement une note commune et en y faisant pointer tous mes outils.
- [[Flux/Dev|Dev]] - J'ai essayé Talon Voice, il y a besoin d'un `AppIndicator`. Je vais chercher quelques scripts pour voir ce que ça peut donner.
- Aujourd'hui j'ai essayé de remplacer mon calendrier par [[Amie]] : ça marche plutôt bien
- [[Flux/Boulot|Boulot]] - Journée assez active car pas mal de soucis à gérer.
- [[Flux/Dev|Dev]] - Soumission d'[[Obsidian Feeds]] pour revue et devenir un plugin communautaire officiel ! C'est un jalon important et un premier pas dans la communauté de développeurs Obsidian.
- [[Flux/Mental|Mental]] - J'étais de meilleure humeur aujourd'hui, accomplir des tâches dues depuis longtemps a fait du bien. Les 3 tâches que je m'étais notées comme prioritaires sont faites !
- [[Flux/Boulot|Boulot]] - Je change le format de ma note quotidienne pour quelque chose de plus orienté listes.
```

My topic notes are configured to display the feed like this:

```markdown
- [[2023-S45 > 2023-11-08]] - [[Flux/Dev|Dev]] - J'ai essayé Talon Voice, il y a besoin d'un `AppIndicator`. Je vais chercher quelques scripts pour voir ce que ça peut donner.
- [[2023-S45 > 2023-11-08]] - [[Flux/Dev|Dev]] - Soumission d'[[Obsidian Feeds]] pour revue et devenir un plugin communautaire officiel ! C'est un jalon important et un premier pas dans la communauté de développeurs Obsidian.
- [[2023-S44 > 2023-11-03]] - [[Flux/Dev|Dev]] - J'ai ouvert une PR pour la refacto/simplification du plugin [[Obsidian Feeds]] ! On en a un peu discuté avec [[Personnes/Lukas Petry|Luke]] et on est d'accord tous les deux que ça doit rester le plus simple possible. J'attends la review de haste.
```

Some older notes of mine have the Topic link alone on a first bullet point then the notes as children bullets. I will probably refactor that to have the same style everywhere but I feel like it's worth mentioning.

## Projects

I keep Project-related notes where I want to have a log of what happened for a given project. I currently simply drop a feed block in my project notes and it produces this kind of output:

```
- [[2023-S45  > 2023-11-08]] - [[Flux/Dev|Dev]] - Soumission d'[[Obsidian Feeds]] pour revue et devenir un plugin communautaire officiel ! C'est un jalon important et un premier pas dans la communauté de développeurs Obsidian.
- [[2023-S44  > 2023-11-08]] - [[Flux/Dev|Dev]] - J'ai ouvert une PR pour la refacto/simplification du plugin [[Obsidian Feeds]] ! On en a un peu discuté avec [[Personnes/Lukas Petry|Luke]] et on est d'accord tous les deux que ça doit rester le plus simple possible. J'attends la review de haste.
- [[2023-S42  > 2023-11-08]] - [[Flux/Dev|Dev]] - J'ai fait une première PR sur [[Obsidian Feeds]] pour pouvoir plus facilement symlinker la vue depuis mon clone du dépôt et ajouter des styles - ça casse mes vues sur mobile par contre 😬
- [[2023-S42 > 2023-11-08]] - Je pense que c'était une erreur de mettre la vue dans un dossier spécifique dans le dépôt d'[[Obsidian Feeds]]. Utiliser un lien symbolique ne marche pas sur mobile. Je devrais plutôt tout mettre à la racine et faire un clone Git.
- [[2023-S41 > 2023-11-08]] - On est arrivés à convaincre une modératrice du [[Obsidian Discord|Discord d'Obsidian]] de créer un thread pour le [[Obsidian Feeds|système de flux]] de [[Personnes/Lukas Petry|Luke242]] !
```

## What I would like/need that is not possible yet

- For my topic notes, I would like to be able to remove the prefix from each bullet point

**Comment by menagerie198** [comment]
Here you go... if you need more I will dig it up...
I use a daily note (named `2023-11-09` etc) where I use  a kind of bullet journal/interstital method. Each entry is time-logged, thus
`## 15:02 -- Important thing
- Something important happened in [[project A]]`

If that entry starts to take up more than a line or two, I carry on in a 'side-note', thusly
`[[2023-11-09 Side Note A]]'. It is generally in this note where I put any associated tasks (using Tasks plugin).

Then in the 'Project A' file I have the 'Feed' under a `## heading`, rendered thusly by your fine plugin... 

```
## DNP Feed
[[2023-11-09]] (1)
    Something important happened in [[Project A]].
[[2023-11-09 Side Note A]] (1)
    Something important about the thing, that goes on for more than two lines, and may contain a ToDo:
    [ ] Do the important thing 📅 2023-11-12
```

I also use 'FleetingNotes' app/plugin to save relevant weblinks. I find it easiest to #tag those web-bookmark notes in my browser when I save them (FleetingNotes provides a drop-down of previously used #tags). When I import them into Obsidian, they then get picked up by 'Feeds' from those tags (`#importantThing`, etc). I also try to remember to add `[[Project A`]]` - but I am less efficient at this than the tagging.

**Comment by mariomui** [comment]
I combine my daily notes so i dont necessarily have a orderly sytem.

---
---

# Combined Document

- List of names that have war origins

* Aldric:
  - Of Germanic origin, it means "old ruler" or "wise leader," attributes often valued in wartime.
* Bernard:
  - Derived from the Germanic elements "ber" (bear) and "hard" (brave, strong), it can be associated with strength in battle.
* Briana:
  - A feminine name that is a variant of "Brian," which means "noble" and can be associated with leadership in wartime.
* Conrad:
  - $\color{aqua}{\coloneqq}$ 🇩‍🇪 "bold counsel" or "brave adviser."
* Ethan:
  - $\color{aqua}{\coloneqq}$ 🇮‍🇱 it means "strong," which can be associated with physical and mental strength in challenging situations, including wars.
* Gerard: From the Germanic name "Gerhard," which means "brave spearman."
* Louis: Derived from the Germanic name "Chlodovech," composed of "hlud" (fame) and "wīg" (war), meaning "famous warrior."
* Theodore: From the Greek name "Theodoros," which combines "theos" (god) and "dōron" (gift), it can be interpreted as "gift of God" in the context of strength in battle.
* Valentina: Derived from the Latin word "valens," which means "strong" or "healthy," it can imply strength in various contexts, including battles.

- [[20--apis,b.t.-ObsidianMD-app,etc]]
  - 📝 [GitHub - nothingislost/obsidian-query-control: An experimental Obsidian plugin that adds controls to embedded queries](https://github.com/nothingislost/obsidian-query-control)
    - [[list-of-coders,b.t.-github#nothingislost]] has a plugin that has several nice features.
      - These features include:
        - The ability to collapse all search results when using the embedded query feature view.
        - Undocumented commands such as ViewCreator [main.ts](https://github.com/nothingislost/obsidian-query-control/blob/b7e397f049dacc1a6ff6de7d7b2f2a677a098b16/src/main.ts#L11)

---

> /REDACTED/A_FLEETING_NOTES/2023-010-03_10-13/2023-10-08.MD

---

- That quick draw system is nice. Draw by pushing with the off hand into the already positioned dominant hand

  - 📝 [How Modern Budō Are NO MATCH For Kobudō (Ancient Martial Arts) @-asayamaichidenkai-161 - YouTube](https://youtu.be/8atQUmkie4I?si=5iuN9xpZ-0aQXdOH)
  - ⚙ This fast sheathing works because the dominant hand is in its final position and the off hand is pushing the sheathe on or off the blade. The world is happening to the blade.

- Draw by throwin the sword to the stationary dominant hand
- Use the spinning body to impart inertia to unsheathe the sword so that you can spend the rest of your energy on the counterattack.

- spin throwing vs non spin throwing methods on throwing knives

  - spin requires timing , imagine hitting your enemy with the butt end of a kunai/shuriken? embarassing.

- Kata only practice that lures the opponent to hitting the head.

  - 📝 [Proving How Using Katana with One Hand is Stronger Than Two - YouTube](https://youtu.be/wP0K8anJCxc?si=eKKhiqXL2T6617ft&t=279)
  - ⚖ Looks cool , has cool name called han-getsu or the half moon technique but if the opponent aims for the wrist, you dead. (only useful in practice, although many highly skilled practiioners deride it saying [[practice-that-does-not-ape-reality-trains-muscle-memory-to-behave-wrongly-in-reality]]).

- Some sword schools forbid kicking above the waist as that leads to unstable foundation. What is the point of kicking the chest? they say.

- [They are Violating a Taboo in Our Ryuha | Kobudo Master Reacts to "The Last Samurai" Fighting Scenes - YouTube](https://youtu.be/YFYkWn8mt7A?si=376BT7O13ML2B_qY&t=603)

  - You would never hold a sword parallel to your chest to block a swinging blade because...
    - That blade attacking you would be thrusting.
    - 🤔 It wcould be interesting to bend the blade when are on the ground so that the coil action could snap the thrust to your chest.

- only squat during sword fights when the end position leaves you at an end state farther away from the enemy so that you have time to return to standing (and defensible) position.

- katori shinto ryu

  - kenjuitsu tradition
  - Maki uchi where you shift your arms so that the over head forehead slash has the most power in front of you, sortah like a really powerful forcefield. (dangerous though, when you miss the defense)
  - Kaiken

- Overseer <-- download manager for plexo for user requests to plex

---

> /REDACTED/A_FLEETING_NOTES/2023-010-03_10-13/2023-10-09.MD

---

- Fighting technique training
  - [Boxing tip. How to prevent pulling the cross back before firing YouTube](https://youtube.com/shorts/DAMHwBc_zCw?si=E3d_tzbLm4LZL8Zx)
  - The coach will hurt you if you don't always have your guard up. Guard and attack at the same time! If you don't I will slap you!

---

> /REDACTED/A_FLEETING_NOTES/2023-010-03_10-13/2023-10-11.MD

---

---

---

- nice quote from mario
  - 💬 "you know what can mess people up,too? people. A majority of home schooled folks most likely have a good reason to be. In fact, most stuff prollly had a good reason to be stuffed."
- A hand slamming down someone's head causing his feet to burst due to blood cavitation , fictional martial arts technique?
  - 📝 [Cavitation in Bottle at 82,000fps - YouTube](https://www.youtube.com/watch?v=xM6zdim0yk4)

---

> /REDACTED/A_FLEETING_NOTES/2023-010-03_10-13/2023-10-12.MD

---

---

> /REDACTED/A_FLEETING_NOTES/2023-010-03_10-13/2023-10-13.MD

---

- writing concept
  - there was a saying during the warlord era that is appropriate: "In China, your generals will be of three characteristics: Loyal, Competent, and Chinese. Choose up to two.

---

**Comment by magma-chili** [comment]
I don't know if you're considering checkboxes within the scope of bullet points, and I'm still evolving my format, but this is a pretty typical use case:

![image](https://github.com/lukemt/obsidian-feeds/assets/129216868/4b172423-95b5-42a7-b54d-4e9eecdb75fc)

**Comment by madx** [comment]
Thanks everyone for your inputs!

@mariomui So what would you like to extract from this log? The bullets referencing your Obsdian notes?

@magma-chili Very interesting workflow, I see you rely a lot on tags and checkboxes so that definitely has its place!

**Comment by mariomui** [comment]
It would be cool if the root bullet points were sorted automatically by regex.

**Comment by Azeirah** [comment]
What I would really love to see is support for blocks as well, I come from Roam and while I really do love bullet points, it's not Obsidian's core strength.

I typically want use Markdown with all its features instead of being limited to what's reasonable in bullets. So if I have a daily note, I might work on a project, note down a task or two for managing my household and write in my daily journal.

```
# daily note

## [[myProject]] #log

- bla bla
- [ ] bla bla

[!bla](someImage.png)

Bla bla bla lorem ipsum

## [[🏠]]

I feel like the kitchen is hard to keep clean :(

## [[diary]]

...
```

Otherwise, the way the plugin works right now is already quite nice. I'm looking forward to seeing what you're doing. A batteries-included turnkey "everything related to this note right now please" plugin is a really nice addition compared to the low-level power user plugins I see most of the time!

**Comment by madx** [comment]
@Azeirah So in this case here you'd want to have the contents under the `[[myProject]]` heading in your feed note right?

**Comment by Azeirah** [comment]
In short, yes.

Slightly longer, markdown offers hierarchically structured documents. Bullets points are also a hierarchy of sorts.

Each heading creates one layer in the hierarchy, everything "under" the heading should belong to that heading.

IE

```
# Heading 1 [[myProject]]

## Heading 2

Hello world
```

The MyProject feed should basically have all of the above in it.

In a sense indented bullet lists and heading hierarchies are the same data structure. Making them act the same in the feed might be the most natural way to do it.

I really wish Obsidian supported this naturally in its search, but it's very lacking unfortunately :(

**Comment by magma-chili** [comment]
> I don't know if you're considering checkboxes within the scope of bullet points, and I'm still evolving my format, but this is a pretty typical use case:
> 
> ![image](https://user-images.githubusercontent.com/129216868/281836440-4b172423-95b5-42a7-b54d-4e9eecdb75fc.png)

Similar to [Azeirah](https://github.com/Azeirah)'s reply, I'd like to also ask, if it isn't too inconvenient if, it's possible for checkboxes under a tag/heading to show up if that tag/heading isn't included in the checkbox line. i.e.

```md
### #tag [[link]]

- [ ] something related
- [ ] something else related
```

rathre than requiring

```md
- [ ] something related #tag [[link]]
- [ ] something else related #tag [[link]]
```

which would be super helpful so that I don't have to redundatntly type `#tag [[link]]` for every subsequent checkbox

**Comment by madx** [comment]
Based on your answers and on what we've been discussing over on Discord, here's my plan: 

- [ ] Remove `includeFolders` option
- [ ] Remove `excludeFolders` option
- [ ] Change `searchFor` to use a regular Dataview query from which we will extract both tags and link topics automatically. We should be able to have access to the [query AST](https://github.com/blacksmithgu/obsidian-dataview/blob/master/src/api/plugin-api.ts#L254-L265) to find the topics. Folder inclusion/exclusion will be done here.
- [ ] Remove `showCopyFeedButton` and `showOptionsPanel` options. UI will always be present (with pagination and additional filtering options)
- [ ] Have two options for `includeChildren` and `includeAncestors`
- [ ] Have an option to match on headings (with `includeChildren` and `includeAncestors` behaving the same way as lists)
- [ ] Keep `collapseHeader` and make sure it works both for heading-based and list-based feeds.
- [ ] Do not use `taskList` for rendering as it is bad performance-wise. Consider building the UI in React.
- [ ] Add options to customize the output (still unsure if this applies to all types of feeds, maybe a simpler post processing hook entirely customizable by the user would be enough)

I am going to create issues to track all of these and start working on the new Feeds!
Thanks everyone for your input 🙏🏻 
I'm closing this for now, don't hesitate to add a comment or message me on Discord for sharing your practice.
