### ISSUE TITLE
Updating the settings does not trigger an update of the rendered feed

### ISSUE THREAD

**Issue by madx** [lukemt/obsidian-feeds#13]
When a settings is changed in the settings panel, it has no effect on the rendered feed. A manual reload is needed.
Forcing refresh through dataview does not work either.

**Comment by I-Pch** [comment]
I've stumbled upon this too on desktop (Mac) and mobile (iPhone/iPad). 

And when it comes to rendering some changes made, as this could potentially be linked to this issue, I've also noticed that : 

When renaming or moving a note in which the current note is mentioned and displayed into a feed, the changes are only rendered if one uses the command :`Dataview: Drop all cached file metadata` 😊 .

### Example 1: Renaming
If I add `Feeds` into `Note A` and  `Note C` mentions `Note A` and then rename `Note C` into `Note D`: 

→ `Feeds` in `Note A` will still render `Note C` until I manually trigger the command `Dataview: Drop all cached file metadata`.

https://github.com/lukemt/obsidian-feeds/assets/77828085/96a57966-9687-40cd-a37d-d8b01c508848

---
Something similar happens when moving a note (using drag n' drop or Obsidian's native `move file to ...` feature.

### Example 2: Moving
If `Note A` containing the feed is mentioned in `Note B` and I move `Note B` to another location:

→ `Feeds` in `Note A` will render `Note B` but won't acknowledge the new location of `Note B` unless I manually trigger the command `Dataview: Drop all cached file metadata` (once more 😊 ).

https://github.com/lukemt/obsidian-feeds/assets/77828085/b8b2c31b-0cfb-43cf-905d-9a4a86b63a9f

---
This has been seen on MacOS Big Sur 11.7.10 + Obsidian 1.4.16 + Dataview 0.5.64 in a brand new and almost empty vault.
It was also reproduced on iPad (iPadOS 17.1.1 + Obsidian 1.4.16 + Dataview 0.5.64) + same vault.

Thank you for this marvellous plugin which gives me ideas on how I could reorganise some things in my vaults 🙌 !
